### PR TITLE
Proofread docs.

### PR DESCRIPTION
**Pull request by ima-hima**

### CODE REVIEW

**Comment by recursion-ninja** [comment]
Thanks for the documentation review. It looks better. I predictably had some spelling and grammar errors.

These are some things I noticed.

 * [ ] Typeclass(es) should be one word and not two

 * [ ] We should prefer a unicode characters over a HTML escape sequences for em-dashes, apostrophes, negative signs, etc. This is so that the Haddock documentation is readable in multiple forms (source code, HTML, LaTeX, etc).

**Comment by ima-hima** [comment]
Don’t you be telling me how to spell stuff!! Seriously though, I was just deleting hyphens from "data-types” and a couple of “type-classes” probably got caught up in that, because sloppy. 😞

I considered the unicode but was afraid it wouldn’t work. I’ve been wondering the same thing about html for couple of years, too, but as far as I can tell you still need to use the html entities. I did check the Haddock docs and it said it would use them correctly. I can’t remember anymore if it actually suggested them or not.

I’m assuming you made these changes already? If so I’m going to remove my bv-little repo.

e

On 2018, February 20 at 22:41:53, recursion-ninja (notifications@github.com) wrote:

Thanks for the documentation review. It looks better. I predictably had some spelling and grammar errors.

These are some things I noticed.

 Typeclass(es) should be one word and not two

 We should prefer a unicode characters over a HTML escape sequences for em-dashes, apostrophes, negative signs, etc. This is so that the Haddock documentation is readable in multiple forms (source code, HTML, LaTeX, etc).

**Comment by recursion-ninja** [comment]
I didn't make the suggested changes. I was hoping you could make one more commit on this pull request. If not I can do it tomorrow.

**Comment by ima-hima** [comment]
Okay, I'll do it when I get in.

**Pull request merged**
